### ISSUE TITLE
PGPT_OLLAMA_API_BASE is not set?

### ISSUE THREAD

**Issue by bruno-viva** [qdm12/private-gpt#9]
Following up from #5 

Thanks for this! I had to update this in the docker-compose: `PGPT_OLLAMA_API_BASE: http://host.docker.internal:11434`

But now, with the UI mode and the LLM Chat, I get this error with an empty response after submitting a sample:

```
private-gpt-private-gpt-1  | 00:16:41.049 [INFO    ]            uvicorn.access - 172.19.0.1:60168 - "POST /run/predict HTTP/1.1" 200
private-gpt-private-gpt-1  | 00:16:41.050 [INFO    ]            uvicorn.access - 172.19.0.1:60152 - "POST /run/predict HTTP/1.1" 200
private-gpt-private-gpt-1  | 00:16:41.053 [INFO    ]            uvicorn.access - 172.19.0.1:60152 - "POST /run/predict HTTP/1.1" 200
private-gpt-private-gpt-1  | 00:16:41.056 [INFO    ]            uvicorn.access - 172.19.0.1:60152 - "POST /queue/join HTTP/1.1" 200
private-gpt-private-gpt-1  | 00:16:41.059 [INFO    ]            uvicorn.access - 172.19.0.1:60152 - "GET /queue/data?session_hash=h60wow4ofi8 HTTP/1.1" 200
private-gpt-private-gpt-1  | 00:16:41.425 [WARNING ] llama_index.core.chat_engine.types - Encountered exception writing response to history: [Errno -2] Name or service not known
private-gpt-private-gpt-1  | 00:16:41.467 [INFO    ]            uvicorn.access - 172.19.0.1:60152 - "POST /run/predict HTTP/1.1" 200
``` 

Any ideas on what am I missing? Thanks in advance

(attaching image): 
![image](https://github.com/qdm12/private-gpt/assets/56004875/5ecd7676-7825-42ca-8933-b89d2cdcb901)

**Comment by qdm12** [comment]
Your PrivateGPT container fails to reach Ollama for some reason, this is due to DNS (`Name or service not known`) and `host.docker.internal`. Double check that part of things 😉  Sorry I cannot help further really.
